language: csharp
mono: none
dotnet: 3.0
dist: bionic
install:
 - dotnet restore
script:
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover src/Frappe.Net.Test/Frappe.Net.Test.csproj
after_success:
 - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
 - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
 - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
 - echo $TRAVIS_COMMIT
 - echo $TRAVIS_BRANCH
 - echo $REPO_COMMIT_AUTHOR
 - echo $REPO_COMMIT_AUTHOR_EMAIL
 - echo $REPO_COMMIT_MESSAGE
 - echo $TRAVIS_JOB_ID